#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 10 15:50:53 2017

@author: umesh
"""

def applyF_filterG(L, f, g):
    """
    Assumes L is a list of integers
    Assume functions f and g are defined for you.
    f takes in an integer, applies a function, returns another integer
    g takes in an integer, applies a Boolean function,
        returns either True or False
    Mutates L such that, for each element i originally in L, L contains
        i if g(f(i)) returns True, and no other elements
    Returns the largest element in the mutated L or -1 if the list is empty
    """
    # Your code here
    del_vals = [l for l in L if not g(f(l))]

    # in-place removal ov
    for val in del_vals:
        L.remove(val)

    # compute the max or -1
    if L:
        ret_value = max(L)
    else:
        ret_value = -1
    return ret_value


def f(i):
    return i + 2
def g(i):
    return i > 5


#def f(i):
#    return 1
#def g(i):
#    return False

L = [0, -10, 6, 5, 7, -4]

print(applyF_filterG(L, f, g))
print(L)